name: wintest
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          path: JAERO
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          #install: git mingw-w64-x86_64-toolchain autoconf libtool mingw-w64-x86_64-cpputest mingw-w64-x86_64-qt5 mingw-w64-x86_64-cmake mingw-w64-x86_64-libvorbis
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./JAERO/test.sh